config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students
  resources :bank_details
  get 'dashboard/index'

  resources :clients
  resources :projects
  get 'tasks/mark_as_complete'
  resources :tasks
  get 'say/hello'
  get 'say/data'

  root 'clients#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    #create,read,update,delete
    if user.role? "super_admin"
        can :manage, :all 
    elsif user.role? "admin"
        can [:create, :read, :update], :all
    elsif  user.role? "user"
        can :manage, [Client, Project, Task]
    elsif user.role? "client"
        can :read, [Project, Task]
    end    
  end    
             
        
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end

app/models/bank_detail.rb
class BankDetail < ActiveRecord::Base
	belongs_to :client
	validates_presence_of :acc_no
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :project_categories
	has_many :projects, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects,dependent: :destroy
	has_one :bank_detail
	accepts_nested_attributes_for :bank_detail
	belongs_to :user

    validates_presence_of :name, :mobile ,:company, :email
    validates_numericality_of :mobile
    validates_length_of :mobile , is: 10
    validates_uniqueness_of :email
    validates_format_of :email, with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	def list_projects
		Project.where('client_id = ?',self.id)
	end
	def open_projects
		Project.where('client_id = ? AND status = ?',self.id,"open")
	end
	def completed_projects
		Project.where('client_id = ? AND status = ?',self.id,"completed")
	end
	def thisyear_projects
		Project.where('client_id = ? AND start_date >= ? AND start_date <= ?',self.id,Date.today.beginning_of_year,Date.today)
	end
	def lastyear_projects
		Project.where('client_id = ? AND start_date >= ? AND start_date <= ?',self.id,)
	end
	def lastclientpro
    	Project.where('client_id = ? AND (status = ? OR status = ?)',self.id,"completed","on-going")
    end
    def lastpro_task
		Project.where('client_id = ?',self.id,)
	end
	
end

app/models/ivc.rb
puts "Isha Volunteer connect is a platform to connect volunteers and update them about the upcoming events and programs \n to provide an oppurtunity to volunteer."

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :client
	belongs_to :user
	has_many :tasks
	has_many :project_categories
	has_many :categories, through: :project_categories
	validates_presence_of :name, :status
	def projectdec_ongoing
		Project.where('client_id = ? AND start_date = ? AND status = ?',self.id,Date.parse("2015-12-01"),"on-going")
    end
    def firstclient
    	Project.where('client_id = ? AND status = ?',1,"open")
    end
    
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users,through: :permissions
end

app/models/student.rb
class Student < ActiveRecord::Base
	acts_as_paranoid
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
	validates :name, presence: true

	validate :check_due_date

	private 
	def check_due_date
		if !self.due_date.nil? && self.due_date < self.project.start_date
			errors.add(:due_date,"is invalid.Cannot be less than #{self.project.start_date}")
		end
	end	


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks
	has_many :permissions
	has_many :roles, through: :permissions

	def role?(role)
		self.roles.pluck(:name).include?(role)
	end	
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

 load_and_authorize_resource

	before_filter :authenticate_user!
	def index
       @clients = current_user.role?("super_admin") ? Client.all : current_user.clients
	end

	def new
		@client = Client.new
		@bank_detail = @client.build_bank_detail
	end	

	def create
		@client = Client.new(client_params)
		@client.user_id = current_user.id
		if @client.save
			redirect_to clients_path, notice: "Client was successfully created"
		else 
			render "new"
		end	
	end	

	def show
		begin
		@client = current_user.role?("super_admin") ? Client.find(params[:id]) : current_user.client.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		redirect_to clients_path,notice: "Record Not Found"
	end
	end

	def edit
		begin
		@client = Client.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		redirect_to clients_path,notice: "Record Not Found"
	end
	@bank_detail = @client.bank_detail.nil? ? @client.build_bank_detail : @client.bank_detail
   end
		
	end

	def update
		@client = Client.find(params[:id])
		if @client.update_attributes(client_params)
			redirect_to client_path(@client.id),notice:"Successfully updated the client"
		else 
			render "edit"
		end
	end	
	def destroy
		@client = Client.find(params[:id])
		@client.destroy
		redirect_to clients_path,notice: "Successfully deleted the client"
	end

 private 

 def client_params
 	params[:client].permit(:name,:company,:website,:email,:mobile,bank_detail_attributes:[:acc_no,:bank_name,:tin_number])
 end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@clients = Client.all
  end
  def goodbye
  end
  def data
  	@clients = Client.all
  	@projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_details_helper.rb
module BankDetailsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>
<% if @client.errors.any? %>
<div class="error" style="color: red">
<ol>
<% for msg in @client.errors.full_messages %>
<li><%= msg %></li>
<% end %>
</ol>
</div>
<% end %>

<label>Name</label><br/>
 <%= f.text_field :name %><br/>

 <label>Company</label><br/>
 <%= f.text_field :company %><br/>

 <label>Mobile</label><br/>
 <%= f.text_field :mobile %><br/>

 <label>Email</label><br/>
 <%= f.text_field :email %><br/>

<label>Website</label><br/>
 <%= f.text_field :website %><br/>
 <h3>Bank Details</h3>

<%= f.fields_for @bank_detail do |bank| %>

 <label>Account number</label><br/>
 <%= bank.text_field :acc_no %><br/>

 <label>Bank name</label><br/>
 <%= bank.text_field :bank_name %><br/>

 <label>Tin number</label><br/>
 <%= bank.text_field :tin_number %><br/>
<%end%>
 
  <%= f.submit %>
  <% end %>


app/views/clients/edit.html.erb
<h3>Edit<h3>Add Client</h3>
<%= render 'form' %>

app/views/clients/index.html.erb
<h3>Listing Clients</h3>
<%=  link_to "Export to excel",clients_path(format: "xls") %>
<strong> Total number of clients = <%= @clients.count %> </strong>
 <table border = "1">
  <tr>
   <thead>
    <th>#</th>
    <th>Name</th>
    <th>Company</th>
    <th>Website</th>
    <th>Email</th>
    <th>Mobile</th>
    <th>Project count</th>
  </thead>
 </tr>

 <% @clients.each_with_index do |client,index| %>
 <tr>
  <td><%= index + 1 %></td>
  <td><%= link_to client.name,client_path(client.id) %></td>
  <td><%= client.company %></td>
  <td><%= client.website %></td>
  <td><%= client.email %></td>
  <td><%= client.mobile %></td>
  <td><%= client.projects.size %></td>
 </tr>
 
 <% end %>
 </table>
  <%= link_to "Add Client",new_client_path %>

app/views/clients/index.xls.erb
<table border = "1">
  <tr>
   <thead>
    <th>#</th>
    <th>Name</th>
    <th>Company</th>
    <th>Website</th>
    <th>Email</th>
    <th>Mobile</th>
  </thead>
 </tr>

 <% @clients.each_with_index do |client,index| %>
 <tr>
  <td><%= index + 1 %></td>
  <td><%= link_to client.name,client_url(client.id) %></td>
  <td><%= client.company %></td>
  <td><%= client.website %></td>
  <td><%= client.email %></td>
  <td><%= client.mobile %></td>
 </tr>
 
 <% end %>
 </table>
 <%= link_to "Add Client",new_client_url %>

app/views/clients/new.html.erb
<h3>Add Client</h3>
<%= render 'form' %>

app/views/clients/show.html.erb
<h2><%= @client.name %>
<small>
<%= link_to "edit",edit_client_path(@client.id) %> | 
<%= link_to "destroy",client_path(@client.id),method: :delete,data:{confirm: "Are you sure?"} %>
</small>
</h2>

<p> <%= @client.company %>| <%= @client.website %>|<%= @client.mobile %> </p>


<% if @client.projects.empty? %>
<p> No project found.Add your first project <%= link_to "here" %>
</p>
<% else %>
<%data ={}%>
<h3> Project count = <%= @client.projects.size %></h3>
<ul>
<% for project in @client.projects %>
<li><%= project.id %><%= project.name %></li>
<%= data["#{project.name}"] = project.tasks.size %>
<%end%>

<%= column_chart(data)%>
</ul>
<%end%> 
