config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students
  resources :bank_details
  get 'dashboard/index'

  resources :clients
  resources :projects
  get 'tasks/mark_as_complete'
  resources :tasks
  get 'say/hello'
  get 'say/data'

  root 'clients#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    #create,read,update,delete
    if user.role? "super_admin"
        can :manage, :all 
    elsif user.role? "admin"
        can [:create, :read, :update], :all
    elsif  user.role? "user"
        can :manage, [Client, Project, Task]
    elsif user.role? "client"
        can :read, [Project, Task]
    end    
  end    
             
        
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end

app/models/bank_detail.rb
class BankDetail < ActiveRecord::Base
	belongs_to :client
	validates_presence_of :acc_no
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :project_categories
	has_many :projects, through: :project_categories
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects,dependent: :destroy
	has_one :bank_detail
	accepts_nested_attributes_for :bank_detail
	belongs_to :user

    validates_presence_of :name, :mobile ,:company, :email
    validates_numericality_of :mobile
    validates_length_of :mobile , is: 10
    validates_uniqueness_of :email
    validates_format_of :email, with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	def list_projects
		Project.where('client_id = ?',self.id)
	end
	def open_projects
		Project.where('client_id = ? AND status = ?',self.id,"open")
	end
	def completed_projects
		Project.where('client_id = ? AND status = ?',self.id,"completed")
	end
	def thisyear_projects
		Project.where('client_id = ? AND start_date >= ? AND start_date <= ?',self.id,Date.today.beginning_of_year,Date.today)
	end
	def lastyear_projects
		Project.where('client_id = ? AND start_date >= ? AND start_date <= ?',self.id,)
	end
	def lastclientpro
    	Project.where('client_id = ? AND (status = ? OR status = ?)',self.id,"completed","on-going")
    end
    def lastpro_task
		Project.where('client_id = ?',self.id,)
	end
	
end

app/models/ivc.rb
puts "Isha Volunteer connect is a platform to connect volunteers and update them about the upcoming events and programs \n to provide an oppurtunity to volunteer."

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :client
	belongs_to :user
	has_many :tasks
	has_many :project_categories
	has_many :categories, through: :project_categories
	validates_presence_of :name, :status
	def projectdec_ongoing
		Project.where('client_id = ? AND start_date = ? AND status = ?',self.id,Date.parse("2015-12-01"),"on-going")
    end
    def firstclient
    	Project.where('client_id = ? AND status = ?',1,"open")
    end
    
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :permissions
	has_many :users,through: :permissions
end

app/models/student.rb
class Student < ActiveRecord::Base
	acts_as_paranoid
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
	validates :name, presence: true

	validate :check_due_date

	private 
	def check_due_date
		if !self.due_date.nil? && self.due_date < self.project.start_date
			errors.add(:due_date,"is invalid.Cannot be less than #{self.project.start_date}")
		end
	end	


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :profile
	has_many :clients
	has_many :projects
	has_many :tasks
	has_many :permissions
	has_many :roles, through: :permissions

	def role?(role)
		self.roles.pluck(:name).include?(role)
	end	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all
		 if params[:client_id]
         @projects = client.projects.where('client_id = ?',params[:client_id]) 
     else 
     	@projects = Client.all
     end
     render layout: 'application'
	end

	def new
		@projects = Project.new
	end

	def create
	    @project = Project.new(project_params)
	  if @project.save
	    redirect_to projects_path,notice: "Successfully created the project"
	  else
	  render "new"
	  end
	end
	def show
		@project = Project.find(params[:id])
		@task = Task.new
	end

	private

	def project_params
	params[:project].permit(:client_id,:name,:description,:start_date,:status)	
    end
    	
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@clients = Client.all
  end
  def goodbye
  end
  def data
  	@clients = Client.all
  	@projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_details_helper.rb
module BankDetailsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/projects/index.html.erb
<h3>Listing Projects</h3>
<table border = "1">
<strong>Filter by</strong>
<% for client in Client.all %>
<%= link_to client.name,projects_path(client_id: client.id) %>
<%end%>
<%= link_to "All",projects_path %> 
<tr>
<thead>
<th>Name</th>
<th>Status</th>
<th>Client</th>
</thead>
</tr>
<tbody>
<% for project in @projects%>
<tr> 
<td><%= link_to project.name,project_path(project) %></td>
<td><%= project.status %></td>
<td><%= project.client.try(:name) %></td>
<%end%>
</tbody>
</table>
<%= link_to "Add project",new_project_path %>

app/views/projects/new.html.erb
<h3>Add Project</h3>
<% form_for @project do |f| %>
<label> Client </label><br/>
<%= f.collection_select :client_id,Client.all,:id,:company,prompt: "select" %> <br/>

<label> Name</label><br/>
<%= f.text_field :name,required:true%><br/>

<label> Description</label><br/> 
<%= f.text_area :description %><br/>

<label> Start Date</label><br/> 
<%= f.date_select :start_date,order:[:day,:month,:year] %><br/>
<label>Status</label><br/>
<%= radio_button :status,"open" %> Open
<%= radio_button :status, "on-going" %> On-going
<%= radio_button :status, "completed" %> Completed
<br/>
<%= f.submit %>

<% end %>








app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<p><%= @project.status %> | <%= @project.start_date.strftime("%A,%d %B %Y") %>
| <%= link_to @project.client.try(:name), client_path(@project.client) %>

<h2>Total tasks : <%= @project.tasks.size %></h2>
<% data = [] %>
<% for task in @project.tasks %>
<%= data.push([task.name,@project.start_date,task.due_date]) %><br/>
<% end %>
<%= timeline(data)%>


<h3>Over due tasks</h3>

<ul> <% over_due_tasks = @project.tasks.where('is_completed = ? AND due_date < ?',false,Date.today) %>
 <% over_due_tasks.each do |task| %>
<li>  <%= task.name %>| <%= task.due_date  %>
(<%= link_to "mark as complete",tasks_mark_as_complete_path(task_id: task.id) %>)</li>
  <% end %>
  </ul>

 <h3>Incomplete tasks</h3>
 <ul> 
 <% incomplete_tasks = @project.tasks.where('is_completed = ? AND due_date >= ?',false,Date.today) %>
 <% incomplete_tasks.each do |task| %>
<li> <%= task.name %>| <%= task.due_date  %>
(<%= link_to "mark as complete",tasks_mark_as_complete_path(task_id: task.id)%>)</li>
 <% end %></ul>

 <h3>Completed tasks</h3>
 <ul>
 <% completed_tasks = @project.tasks.where('is_completed = ?',true) %>
 <li> <% completed_tasks.each do |task| %></li>
<%= task.name %> | <%= task.due_date %><br/> 
 <%end%>
 </ul> 

 <h3>Add Task</h3>

 <%= form_for @task do |f| %>
 <%= f.text_field :name,placeholder: "Task name"%><br/><br/>
 <label>Due date?</label> <%= f.date_select :due_date %><br/>
 <label>Is completed?</label> <%= f.check_box :is_completed %> <br/><br/>
 <%= f.hidden_field :project_id,value: @project.id %>
 <%= f.submit %>
 <% end %>